### PR TITLE
Updated Gallery and Activities tab

### PR DESCRIPTION
**Pull request by AmanKant19**
## Updated 
1. Posters in the workshop section in the gallery tab have been updated. 
2. April Ann section of the activities tab has been updated: Now people can see the submissions of the year 2020.
3. added a monarchi poster in the activities tab.
4. Updated posters in the Thursday club section of the Activities tab.
---
@obitors @tejasvaidhyadev @saumyaprabhakar

### CODE REVIEW

**Comment by tejasvaidhyadev** [comment]
Hi @AmanKant19, can you resolve the conflict?
feel free to ping us again

**Comment by AmanKant19** [comment]
> Hi @AmanKant19, can you resolve the conflict?
> feel free to ping us again

**Comment by AmanKant19** [comment]
@tejasvaidhyadev I resolved the conflict.

**Comment by tejasvaidhyadev** [comment]
@obitors, can you help us check @AmanKant19 Merge access

**Comment by tejasvaidhyadev** [comment]
Thanks

**Pull request merged**
