### PR TITLE
updates

### PR DESCRIPTION
**Pull request by saumyaprabhakar**

### CODE REVIEW

**Comment by saumyaprabhakar** [comment]
resolved

**Comment by saumyaprabhakar** [comment]
updated landing images in gallery

**Comment by saumyaprabhakar** [comment]
@tejasvaidhyadev @obitors @AmanKant19

**Comment by tejasvaidhyadev** [comment]
thanks

**Comment by tejasvaidhyadev** [comment]
@obitors  provide them merge access I think they can merge their basic PRs without review
cc @saumyaprabhakar  @AmanKant19

**Pull request merged**
